// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.blue.Service.InspireStream.Client.AutorestClient
{
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for InspireStream.
    /// </summary>
    public static partial class InspireStreamExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='model'>
            /// </param>
            public static IList<TweetsResponseModel> GetTweets(this IInspireStream operations, TweetsSearchModel model = default(TweetsSearchModel))
            {
                return operations.GetTweetsAsync(model).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='model'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<TweetsResponseModel>> GetTweetsAsync(this IInspireStream operations, TweetsSearchModel model = default(TweetsSearchModel), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetTweetsWithHttpMessagesAsync(model, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
