// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.blue.Service.InspireStream.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TwitterAppAccountRquestModel
    {
        /// <summary>
        /// Initializes a new instance of the TwitterAppAccountRquestModel
        /// class.
        /// </summary>
        public TwitterAppAccountRquestModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TwitterAppAccountRquestModel
        /// class.
        /// </summary>
        public TwitterAppAccountRquestModel(string email = default(string), string consumerKey = default(string), string consumerSecret = default(string), string accessToken = default(string), string accessTokenSecret = default(string))
        {
            Email = email;
            ConsumerKey = consumerKey;
            ConsumerSecret = consumerSecret;
            AccessToken = accessToken;
            AccessTokenSecret = accessTokenSecret;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ConsumerKey")]
        public string ConsumerKey { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ConsumerSecret")]
        public string ConsumerSecret { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AccessToken")]
        public string AccessToken { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AccessTokenSecret")]
        public string AccessTokenSecret { get; set; }

    }
}
