// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.blue.Service.InspireStream.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TweetsResponseModel
    {
        /// <summary>
        /// Initializes a new instance of the TweetsResponseModel class.
        /// </summary>
        public TweetsResponseModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TweetsResponseModel class.
        /// </summary>
        public TweetsResponseModel(System.DateTime date, string tweetId = default(string), string title = default(string), string userImage = default(string), string tweetImage = default(string), string author = default(string), string accountId = default(string), string tweetJSON = default(string))
        {
            TweetId = tweetId;
            Title = title;
            UserImage = userImage;
            TweetImage = tweetImage;
            Date = date;
            Author = author;
            AccountId = accountId;
            TweetJSON = tweetJSON;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TweetId")]
        public string TweetId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Title")]
        public string Title { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UserImage")]
        public string UserImage { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TweetImage")]
        public string TweetImage { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Date")]
        public System.DateTime Date { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Author")]
        public string Author { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AccountId")]
        public string AccountId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TweetJSON")]
        public string TweetJSON { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
